spring:
    datasource:
        url: "jdbc:mariadb://localhost:3306/shopbra"
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    redis:
        host: localhost
        port: 6379
        timeout: 10000
    cache:
        type: redis