spring:
    application:
        name: "ShopBra"
    datasource:
        url: "jdbc:mariadb://localhost:3306/shopbra"
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    cache:
        type: redis
server:
    port: 3000
    
logging:
    level:
        org.springframework: INFO
        br.com.shopbra: INFO